### ISSUE TITLE
Read/write text instead of HEX

### ISSUE THREAD

**Issue by hyousef** [tessel/rfid-pn532#21]
How can I write "Text" instead of the HEX code, and how can I read that text again, after writing it

**Comment by johnnyman727** [comment]
@hyousef, have you checked out [this reading/writing example?](https://github.com/tessel/rfid-pn532/blob/master/examples/mifareClassic.js)

**Comment by hyousef** [comment]
Yes @johnnyman727, I did, and want to replace the 

var new_data = [0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,0xff];

by "normal text", like name and so on!

**Comment by johnnyman727** [comment]
@hyousef we should probably update this API to use Buffers, but in any case, it sounds like you need to convert a string to array of bytes. Check out [this StackOverflow answer](http://stackoverflow.com/a/6226756) for guidance on how to do that.

**Comment by hyousef** [comment]
@johnnyman727  I read that one, and made my function that convert the string into Hex, and the Hex into String as shown here http://jsfiddle.net/hyousef/8k5djgcx/

in the RFID example, I wrote this:

var new_data = "new Data";

    var afterAuth2 = function(err){
      if (err) {
        console.log("Auth error", err);
        rfid.startListening();
      } else {
        console.log('Write new data');
        rfid.mifareClassicWriteBlock(addr, new_data.encodeHex(), afterWrite); // <<<---------
      }
    };


and got the below errors:
/app/node_modules/rfid-pn532/index.js:519: attempt to perform arithmetic on local 'checksum' (a string value)

hasan@hasan-HP-ENVY-15-x360-PC:~/tessel-code/rfid$ tessel run rfid.js
TESSEL! Connected to TM-00-04-f0009a30-004d4747-244225c2.
INFO Bundling directory /home/hasan/tessel-code
INFO Deploying bundle (1.03 MB)...
INFO Running script...
Ready to read RFID card
Card found!
UID: 6e912400
Start auth #1
Read old data
Read error Error: invalid packet
Card found!
UID: 6e912400
Start auth #1
Auth error Error: invalid packet
Card found!
UID: 6e912400
Start auth #1
Read old data
Start auth #2
Write new data
/app/node_modules/rfid-pn532/index.js:519: attempt to perform arithmetic on local 'checksum' (a string value)
hasan@hasan-HP-ENVY-15-x360-PC:~/tessel-code/rfid$

**Comment by johnnyman727** [comment]
@hyousef the functions you found online return an array of one character strings. The checksum inside the driver is try to add together all of the bytes of the input but it can't add a string to an integer. If you were running vanilla io.js or Node.js it would be able to do that but not with the desired result (0 + 's' = '0s') so the Tessel runtime is actually stopping you from inputting the wrong kind of data because of that incompatibility.

It seems like what you want to do is actually really simple. To encode:
```.js
var new_data = new Buffer('new Data');
```
And to decode:
```.js
returnedBuffer.toString();
```

**Comment by hyousef** [comment]
I got this error:

Write new data
/app/node_modules/rfid-pn532/index.js:516: attempt to perform arithmetic on a table value

**Comment by hyousef** [comment]
@johnnyman727 I entered manually the following:

var new_data = [0x48,0x65,0x6c,0x6c,0x6f];  // That is: Hello
    var afterAuth2 = function(err){
      .
      .
        console.log('Write new data: '+ new_data); 
      .
    };

and got the console output as below, it looks the code not writting anything, and the 'new data' and 'old data' is always same!:

Write new data: 72,101,108,108,111
Start auth #3
Read new data
New data <Buffer a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af ff>
Old data a1a2a3a4a5a6a7a8a9aaabacadaeafff

**Comment by johnnyman727** [comment]
@hyousef can you share your entire code in a gist? It will be easier to debug.

**Comment by hyousef** [comment]
@johnnyman727  sure, https://gist.github.com/hyousef/0effd5a0ce54d41dd5c7

**Comment by johnnyman727** [comment]
@hasan3ysf ,

It looks like the data blocks need to be 16 bytes in length in order to work properly. It is a bug that we don't throw an error, automatically concat remaining bytes, or at least document that requirement.

If you switch:
```
var new_data = [0x48,0x65,0x6c,0x6c,0x6f]; // That is: Hello
```
to
```
var new_data = [0x48,0x65,0x6c,0x6c,0x6f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff];
```

It should work. I've verified this with the hardware.

@EvanSimpson can you confirm that writes need to be 16 bytes long?

**Comment by hasan3ysf** [comment]
@johnnyman727  I made this function to convert my text into hex of 16 bytes http://jsfiddle.net/hyousef/8k5djgcx/3/, will check it with the tessel tonight.

To how many block can I write in the RFID card, and how can I know there addresses?

**Comment by johnnyman727** [comment]
@hasan3ysf the card that comes with the RFID module is 1kb so there should be 1024/16 = 64 available addresses.

**Comment by hasan3ysf** [comment]
@johnnyman727  I adjusted my gist https://gist.github.com/hasan3ysf/0effd5a0ce54d41dd5c7 

The functions I made to convert to/from Hex, it shows correct output, but fail to write to the RFID block, I got the error msg: 
     /app/node_modules/rfid-pn532/index.js:519: attempt to perform arithmetic on local 'checksum' (a string value)

full output is below:

    D:\Tessel.01>tessel run mifareClassic.js
    TESSEL! Connected to TM-00-04-f0009a30-004d4747-244225c2.
    INFO Bundling directory D:\Tessel.01
    INFO Deploying bundle (72.00 KB)...
    INFO Running script...
    Ready to read RFID card
    Card found!
    UID: 6e912400
    Start auth #1
    The Hexa Code is: 0x49,0x74,0x65,0x6d,0x20,0x43,0x6f,0x64,0x65,0x3a,0x20,0x32,0x
    33,0x34,0x35,0xff The original string is:  Item Code: 2345
    Read old data
    Old data <Buffer 48 65 6c 6c 6f ff ff ff ff ff ff ff ff ff ff ff>
    Start auth #2 
    Write new data
    /app/node_modules/rfid-pn532/index.js:519: attempt to perform arithmetic on local 'checksum' (a string value)

    D:\Tessel.01>

**Comment by johnnyman727** [comment]
@hasan3ysf, I don't have hardware in front of me but it looks like your `encodeHex` function is creating an array of ascii representations of the hex value of the bytes:
```.js
 bytes.push('0x'+this.charCodeAt(i).toString(16));
```
You should be pushing the actual byte data
```
bytes.push(this.charCodeAt(i)
```

**Comment by hasan3ysf** [comment]
@johnnyman727 it is fine if the data is 16 bytes, but if less I need to add something to make them 16, in my code I used:

    for (var i = 0; i < 16; ++i) {
       if(i < this.length) 
          bytes.push(this.charCodeAt(i));
          else bytes.push('0xff');
    }

but the bytes.push('0xff'); still make the same error,, so now I've look for something to use here :(

**Comment by johnnyman727** [comment]
Glad that it works.

In terms of knowing what address you're reading/writing to, that is [number passed as the first](https://gist.github.com/hasan3ysf/0effd5a0ce54d41dd5c7#file-tesselrfid-js-L38) argument to reads and writes.
