### ISSUE TITLE
rfid firmware implementation

### ISSUE THREAD

**Issue by seletiur** [tessel/rfid-pn532#29]
Hello everybody,

Shouldn't rfid-pn532 have a firmware implementation in C similar to this [https://github.com/tessel/ambient-attx4/blob/master/firmware/src/ambient-attx4.c](url) ?

thanks in advance,
Rui

**Comment by johnnyman727** [comment]
Hi @seletiur, the RFID pn523 IC that is used on the RFID module exposes an I2C API that was implemented by the manufacturers of the integrated circuit. We only needed to send properly formatted I2C requests to get the data.

The Ambient and IR module were unique in that we custom designed the sensor and firmware that read data from them. Does that make sense?

**Comment by seletiur** [comment]
It makes perfect sense, thank you ;)
