### ISSUE TITLE
No data with Tessel firmware v0.0.13

### ISSUE THREAD

**Issue by M165437** [tessel/rfid-pn532#30]
There seems to be an issue with Tessel firmware v0.0.13. The `data` event never gets fired. The module’s led does blink when a card enters its field.

**Comment by johnnyman727** [comment]
@M165437 can you confirm this was working with `v0.0.12`?

**Comment by otothea** [comment]
I am having the same issue. On Tessel firmware v0.0.13, I get the 'ready' callback but 'data' never fires. I can confirm if I downgrade to firmware v0.0.12 it works.

**Comment by M165437** [comment]
Right, downgrading helps. `t2 update --force -v 0.0.12`

**Comment by johnnyman727** [comment]
I'm guessing this is a regression caused by https://github.com/tessel/t2-firmware/commit/9dd0ef32d314eefb0391d4bba2d7aab794207e6d. 

@joshdudley would you be able to investigate? I'm not sure if you have an RFID module.

**Comment by johnnyman727** [comment]
Who's that's @dudleyjosh :)

**Comment by johnnyman727** [comment]
*whoops 

GitHub on mobile is hard.

**Comment by dudleyjosh** [comment]
@johnnyman727, I don't have an RFID module, but I am trying to troubleshoot it.

The only pin interrupt used in the RFID module code is `pin.once('low', function(){})` and I didn't make any changes related to the 'low' or 'high' events.

I get the same behavior for both `0.0.12` and `0.0.13` when I try to run a simple button test using the `low` event... the event fires right after the test program starts without me ever touching the button I have hooked up?

Pin `low` test (same pin used in RFID module)
```javascript
var tessel = require('tessel');
var pin = tessel.port['A'].digital[2];
pin.input();

pin.once('low', function() {
    console.log('I am low');
});
```

However, the `high` event seems to work fine.

Pin `high` test (same pin used in RFID module)
```javascript
var tessel = require('tessel');
var pin = tessel.port['A'].digital[2];
pin.input();
pin.pull('pulldown');

pin.once('high', function() {
    console.log('I am high');
});
```

So, there seems to be an issue with both `0.0.12` and `0.0.13` with regards to the `low` event getting fired on startup, but this doesn't really help with the specific issue at hand.

I'll keep testing as I much as I can (which might not be much) this weekend.

**Comment by dudleyjosh** [comment]
@johnnyman727 @rwaldron I was looking into this issue some more and I discovered that I now have issues using the accelerometer module with firmware v0.0.13 too. It seems to lock up after a random period of time with v0.0.13 but not with v0.0.12, including one time where it was returning accelerometer data but only the accelerometer data from the position it was in when it started up (same xyz data was emitted repeatedly). Could it be something related to the I2C changes that were part of firmware v0.0.13?

I was testing by running the example code `t2 run accel.js` over and over again.

```javascript
var tessel = require('tessel');
var accel = require('accel-mma84').use(tessel.port['A']);

// Initialize the accelerometer.
accel.on('ready', function () {
// Stream accelerometer data
    accel.on('data', function (xyz) {
        console.log(
            'x:', xyz[0].toFixed(2),
            'y:', xyz[1].toFixed(2),
            'z:', xyz[2].toFixed(2)
        );
    });

});

accel.on('error', function(err){
    console.log('Error:', err);
});
```

**Comment by johnnyman727** [comment]
I got a hold of an RFID module and didn't have problems with either firmware version (`0.0.12` or `0.0.13`). I haven't been able to reproduce any issues yet.

**Comment by alarner** [comment]
I am having the same issue here on firmware 0.0.13 but it seems to work fine on 0.0.12. Another thing to note is that on 0.0.13, while there is no indication that the RFID is being detected within my code, I do get the blinking light when the RFID card is near the reader on the board itself.

**Comment by cvallance** [comment]
Hey, just wanted to poke my nose in here to say I have the same issue and can also confirm that downgrading to 0.0.12 fixes the issue.

**Comment by alarner** [comment]
Is there any fix coming for this? I have another module that I think will only work with 0.0.13, so I'd love to be able to upgrade and use both modules on the same project.

**Comment by johnnyman727** [comment]
@alarner I don't believe anyone is working on this right now. I don't have the RFID module (or time, for that matter) to pitch in. If you wanted to investigate, you could check out the differences made in the `tessel-export.js` file made between revisions. That file lives at `/usr/local/node/tessel-export.js` on T2 (I think...) if you wanted to fiddle with it.

**Comment by alarner** [comment]
@johnnyman727 I'm taking a look at this and have managed to install custom built firmware from the t2-firmware repo (I think). Is there a good way to debug / get console.log statements to display somewhere? Like a log file that I can tail or something?

**Comment by johnnyman727** [comment]
@alarner you should be able to see any `console.log`s from [the Tessel Driver](https://github.com/tessel/t2-firmware/blob/1d3e13931d9d668013e5446330c74faa09477c17/node/tessel-export.js). In fact, you shouldn't even need to install custom firmware - you can just ssh in (`t2 root`) to your Tessel and edit the `tessel-export.js` file with nano. Alternatively, edit the file in a decent text editor on your host machine and `scp -i ~/.tessel/id_rsa root@YOUR_TESSEL.local:/usr/local/node/tessel-export.js local_tessel_export.js`

If you have already `run ` script on the T2, you can run it from the shell with `node /tmp/remote-script/index.js` (or whatever the entrypoint filename to your project is).

**Comment by alarner** [comment]
@johnnyman727 I believe I've found a fix to this issue and submitted a PR: https://github.com/tessel/t2-firmware/pull/203

**Comment by dudleyjosh** [comment]
@alarner I'm glad you found what looks like a simple fix to the issue on this... clearly I was mistaken when I said "The only pin interrupt used in the RFID module code is pin.once('low', function(){}) and I didn't make any changes related to the low or high events." earlier in this conversation. I too am trying to fully understand exactly why it makes a difference?
